# Generated by Django 5.0.4 on 2024-04-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subtype', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('size', models.CharField(max_length=25)),
                ('range', models.CharField(max_length=25)),
            ],
        ),
    ]
